### ISSUE TITLE
host cannot use wireguard network

### ISSUE THREAD

**Issue by ecsuae** [cmulk/wireguard-docker#29]
i am using your code to connect to my wireguard server i can see in docker logs that interface is configured and i can ping the client ip from wireguard server, i have 3cx pbx configured on the host ,if i use --network host i can ping wireguard server from host but my pbx stops working ,if i do not use --network host then pbx is working fine but i cannot access wireguard network from host.My only requirement is  to allow pbx communicate with other network devices through wireguard.Is there a way i can make host communicate with wireguard network devices ? i tried to add route with ip route command ,still cannot ping any device across wireguard. Also how can i connect to the container to run commands ? docker exec and docker -it do not work with your conatiner.

**Comment by cmulk** [comment]
Not sure exactly what you are describing but I suspect the issue is with the way docker internal networking works in normal mode (without `--network host`). Docker containers use an internal IP space and traffic exiting is masqueraded. In other words the host does not know the route back to other devices that are at the far end of the VPN tunnel.

You can connect to the container with `docker exec -it <container_name> sh`
