### ISSUE TITLE
Need Help With Setting Up Docker

### ISSUE THREAD

**Issue by ghost** [cmulk/wireguard-docker#6]
Hey,
I need help with Docker on one of my repo can you please help me out.

https://github.com/complexorganizations/wireguard-installer-manager/pull/146

I am trying to add docker support but i am very new to docker.
Any Commits is welcome.

- Prajwal

**Comment by cmulk** [comment]
Unfortunately it's not a very simple thing to get this working in docker. Since wireguard requires kernel modules on the host, the module install portion of your script is not going to work in docker unless the docker container is the exact same version as the host. I think the best thing you could do is split the script or add flags so that there is a "install module only" option that gets run on the host (one time) and a "module already installed" option compatible with running insider the docker container. Would take a decent amount of restructuring for you though
